services:
  postgres:
    image: postgres:16.0-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    build:
      context: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
      VIRTUAL_HOST: ${BACKEND_DOMAIN}
      LETSENCRYPT_HOST: ${BACKEND_DOMAIN}
      VIRTUAL_PORT: ${APP_PORT}
    env_file: .env
    depends_on:
      - postgres

volumes:
  db-data:
